// Component exports - following clean code principles
export { AddItemForm } from './AddItemForm'
export { AutoComplete } from './AutoComplete'
export { CategorySection } from './CategorySection'
export { CategorySelector } from './CategorySelector'
export { ItemActions } from './ItemActions'
export { NotificationBanner } from './NotificationBanner'
export { ReceiptScanner } from './ReceiptScanner'
export { ShoppingItemComponent } from './ShoppingItemComponent'
export { SuggestionItem } from './SuggestionItem'
export { ActionButton, ActionButtonGroup } from './ActionButton'
export { Card, CardHeader, CardBody, CardFooter } from './Card'

// Re-export existing components
export { FadeIn, SlideUp } from './Animations'
export { CategoryHeader } from './InteractiveEmoji'
export { DataExport } from './DataExport'
export { EnhancedStatistics } from './EnhancedStatistics'
export { Header } from './Header'
export { QuickAddButtons } from './QuickAddButtons'
export { QuickListCreator } from './QuickListCreator'
export { SmartSuggestions } from './SmartSuggestions'
export { Tutorial } from './Tutorial'
